name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-bun@v2
        with:
            bun-version: latest

      - name: Get dependencies
        run: bun install

      - name: Run Unit tests
        run: bun run test:unit

      - name: Run integration Tests
        run: bun run test:int

        env:
          ENVIRONMENT: test
          LOG_LEVEL: silent
          DATABASE_URL: file:test.db
